### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by charlesmilette** [ryu1kn/vscode-partial-diff#1]
It throws me the following error:
```
Impossible d'ouvrir 'partial-diff' : Fichier introuvable (\\C:\Users\Charles\AppData\Local\Temp\partialDiff-116512-9804-15ry195.iv9bai3sor) (2 erreurs au total).
```

**Comment by ryu1kn** [comment]
Sorry I've just noticed your message, and thanks for contacting me.
I noticed the bug yesterday and fixed it. Could you try with v0.0.4?

**Comment by charlesmilette** [comment]
Yep. It worked.

**Comment by ryu1kn** [comment]
Thanks for confirming it :)
