### ISSUE TITLE
Feature Request: Compare two open tabs with single command

### ISSUE THREAD

**Issue by kiddailey** [ryu1kn/vscode-partial-diff#11]
Great extension, thank you!  The only thing I wish this had was a command to simply compare two open tabs in a single step rather than having to set the selection for the first tab, then navigate to the second tab to perform the comparison.

In other words, a new command labeled "Compare Open Tabs" or similar that when selected, automatically compares the active tab with the next/nearest tab.

I'm not sure if this is even possible, but it would be awesome if it was :)

**Comment by ryu1kn** [comment]
Thanks for the suggestion and sorry for my slow response!

There seem to be some cases not too obvious how the command should work:

* When there are 3 tabs opened side-by-side, it's not too obvious which 2 of will be compared?
  a. Compare against the next tab? (if the current tab is the last tab, compare with previous tab)
  b. Compare the current tab against the one that was previously focused?
* When there are multiple tabs open but not side-by-side (i.e. 1 of them is occupying the whole area), should the command still execute the comparison?

**Comment by kiddailey** [comment]
Maybe if more than two tabs are open, it simply does not perform the comparison and displays a message?

If you want to compare while more than two tabs are open in this case, you'll have to manually select the tabs as you do now.

**Comment by hrvoj3e** [comment]
When working in split screen mode (only two splits - left and right).
Compare active tab on left side with active tab on right side - that is it - the most common case I have.

Hope this gets implemented soon.

**Comment by ryu1kn** [comment]
Maybe we can utilise the new QuickPick API introduced in the last VS Code release (v1.22) to choose 2 tabs.

> ### Multi-Select QuickPick
> We have added an option to the QuickPick API that makes return a list of picked items with a new UI that allows the user to pick any number of items:
> 
> ![](https://code.visualstudio.com/assets/updates/1_22/multi-select-quickpick.png)

https://code.visualstudio.com/updates/v1_22

**Comment by ryu1kn** [comment]
But if what we want is a single user action to compare the currently openend 2 tabs, we can introduce a command that only solves this very requirement.

**Comment by ryu1kn** [comment]
Landed as v0.6.0!
