### ISSUE TITLE
Compare with Clipboard doesn't work properly on Windows 10

### ISSUE THREAD

**Issue by ctinghino** [ryu1kn/vscode-partial-diff#12]
Everytime I try the option to _Compare Text with Clipboard_ I see all the file differs from the clipboard.
This happens even if I compare a file with itself.
I'm on Windows10, vscode version 1.15.1

I disabled the extension

**Comment by ryu1kn** [comment]
Could it be because of like newline character difference?

**Comment by quasarea** [comment]
indeed it is, it looks like it converts \r\n into \n in clipboard and diff it against \r\n in source

**Comment by VicCarLs** [comment]
I have the same problem.  When I copy text from a file with \r\n, it is \n on the clipboard.  Can you add an option to compare ignoring carriage returns?

**Comment by ryu1kn** [comment]
Thanks guys. Yeah, we need to do something about it otherwise **Compare Text with Clipboard** function on Windows 10 is pretty useless.

I had a look at issues on `clipboardy` which Partial diff internally uses for clipboard interaction. There are several issues reported about Windows and EOL characters. I'll see if using the latest version of clipboardy fixes the problem first.

**Comment by ryu1kn** [comment]
* Windows 10
* VS Code v1.16.1
* Partial Diff v0.3.2

1. Open a file
1. Copy the file contents into clipboard with `Ctrl+C`
1. Execute "Compare Text with Clipboard" command
1. Get the following diff view where there should be no diff

![unnamed](https://user-images.githubusercontent.com/1505715/31054195-363806de-a6f9-11e7-8d93-638332fed5bb.png)

**Comment by ryu1kn** [comment]
> I'll see if using the latest version of clipboardy fixes the problem first.

Updated v1.1.2 to v1.1.4. Didn't fix the problem.

**Comment by ryu1kn** [comment]
As reported in https://github.com/sindresorhus/clipboardy/issues/27 , getting `\r\r\n` for EOL

**Comment by ryu1kn** [comment]
Released as v0.3.3. It would be great if you can test it out @quasarea @VicCarLs 😉

**Comment by quasarea** [comment]
Works great, thanks!

**Comment by ryu1kn** [comment]
Thanks for confirming it 👍
