### ISSUE TITLE
Marketplace gif is broken

### ISSUE THREAD

**Issue by corinblaikie** [ryu1kn/vscode-partial-diff#13]
The visual studio market place html @ 
https://marketplace.visualstudio.com/items?itemName=ryu1kn.partial-diff

is referencing an old gif that doesn't exist anymore:
https://raw.githubusercontent.com/ryu1kn/vscode-partial-diff/master/images/select-2-texts-and-take-diff.gif

instead of:
https://raw.githubusercontent.com/ryu1kn/vscode-partial-diff/master/images/public.gif

**Comment by ryu1kn** [comment]
Wow, thanks for reporting it!

**Comment by ryu1kn** [comment]
Published the fix as v0.3.2 👍
