### ISSUE TITLE
Language selection only works on right-hand side of diff

### ISSUE THREAD

**Issue by joeskeen** [ryu1kn/vscode-partial-diff#14]
When comparing larger chunks of text, it's nice to be able to set the language to get syntax highlighting.  When comparing files, VSCode does this for us automatically (based on the file type).  When setting the language in a partial diff, however, it only sets the language for the right-hand side, leaving the left-hand side as 'plain text'.

![image](https://user-images.githubusercontent.com/12286274/30458443-da0c6ea6-9968-11e7-8ab2-67fb6b6a9942.png)

**Comment by joeskeen** [comment]
It looks like this is a vscode bug (as I tested it with plaintext files in VSCode), so I'm going to post a bug there.

**Comment by ryu1kn** [comment]
Thanks for also checking the editor behaviour.

I thought partial diff doesn't set the language for neither sides as I'm not sure if vscode can do syntax highlighting correctly if they have only part of text present in the diff view.

**Comment by joeskeen** [comment]
https://github.com/Microsoft/vscode/issues/34408 has been fixed, which fixes this issue! :)
