### ISSUE TITLE
allow diff'ing Multi-cursor selections

### ISSUE THREAD

**Issue by myrdd** [ryu1kn/vscode-partial-diff#16]
**Steps:**

_1. first selection:_

![first selection](https://user-images.githubusercontent.com/4286829/31990761-477da932-b976-11e7-847a-ea62d704710b.png)

_2. Copy the selection (`Ctrl+C`)_

_3. second selection:_

![second selection](https://user-images.githubusercontent.com/4286829/31990877-9fce263e-b976-11e7-907d-d853423b8d49.png)

_4. compare text with clipboard:_

![compare text with clipboard](https://user-images.githubusercontent.com/4286829/31990972-e081a566-b976-11e7-8a74-f371fea2e09d.png)

**Current result:**

![current diff result](https://user-images.githubusercontent.com/4286829/31991044-15cc013a-b977-11e7-8954-0c8adc9d3594.png)

**Expected result:**

![expected diff result](https://user-images.githubusercontent.com/4286829/31991121-43eaf378-b977-11e7-9bb9-7222d50e78a3.png)

---

**[BTW] scenario 2**

When instead using "select text for compare" (step 2) and "compare text with previous selection" (step 4), the outcome is like this:

![diff result of scenario 2](https://user-images.githubusercontent.com/4286829/31991584-6862f74a-b978-11e7-9b0a-cd99f8e2b3cb.png)

---

**[My system]**

* Debian Stretch
* Visual Studio Code
  * Version 1.17.2
  * Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
  * Shell 1.7.7
  * Renderer 58.0.3029.110
  * Node 7.9.0
  * Architecture x64
* Partial Diff
  * Version 0.3.3

**PS:** Thank you for this great extension!

**Comment by ryu1kn** [comment]
Hi @myrdd, thanks for your suggestion with the clear description, specific environment info and very helpful screen images!! 😭 

And yes, at the moment, it doesn't support the multi-cursor selection. Time to support it!

**Comment by ryu1kn** [comment]
Released as v0.4.0! 😃

**Comment by myrdd** [comment]
Wow, great, it works very well! :)

Still, I found a tiny bug: It make a difference if you select the text top-to-bottom or bottom-to-top. I guess you need to consider [`Selection.isReversed`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#Selection.isReversed).

**Comment by ryu1kn** [comment]
> Still, I found a tiny bug: It make a difference if you select the text top-to-bottom or bottom-to-top.

Oh wow, thank you for finding the bug. You're right. Copying & pasting the texts to other place retains the positional order even when I select them from bottom-to-top; so Partial-diff should follow that behaviour.

**Comment by ryu1kn** [comment]
Released as v0.4.1! 😃

**Comment by myrdd** [comment]
Great support! Many thanks!! 👍 🎆 😄

**Comment by ryu1kn** [comment]
You're welcome, thanks for the great suggestion! 😉
