### ISSUE TITLE
Word wrap diff according to user settings

### ISSUE THREAD

**Issue by karland** [ryu1kn/vscode-partial-diff#17]
@ryu1kn Great tool, thank you. I am comparing two books written in Markdown and the diff file does not word-wrap. The diff file ignores all user settings with regard to word-wrapping. This makes it difficult to compare paragraphs that are longer than 80 letters, because you then always have to scroll left and right.

Am I doing anything wrong? Is this difficult to address?

Thank you...

**Comment by ryu1kn** [comment]
Hi @karland , you're right, word-wrap is currently not supported and it would be not easy from Partial Diff point of view... Partial Diff actually relies on VS Code's diff view, and it doesn't support word-wrap at the moment.

https://github.com/Microsoft/vscode/issues/11387

**Comment by ryu1kn** [comment]
Oh, actually this issue is reported as #8. Anyway, thank you for reporting it, it helps me feel how many people are impacted with the issue.

I wonder if I can help vscode on this...

**Comment by karland** [comment]
@ryu1kn Thanks for your fast reply. And if you could help vscode on word-wrap in diffs that would be awesome...
