### ISSUE TITLE
Feature request: toggle normalization rules in diff view

### ISSUE THREAD

**Issue by stepbeta** [ryu1kn/vscode-partial-diff#18]
Re: #15 

If I can push it a little further, would it be possible to enable/disable the rules while in the diff view? Perhaps a little menu with the list of rules and the ability to check/uncheck each one or all of them?

The reason behind this is because, if I diff two files rather than just a few lines, sometimes I want to actually see if the only differences are the ones "hidden" by the rules, and being able to toggle between the two versions (original/normalized) would be incredibly useful!

**Comment by ryu1kn** [comment]
Thanks for raising a separate issue!

**Comment by stepbeta** [comment]
Yours is a very useful extension, it's a pleasure if I can help with so little! :)

**Comment by ryu1kn** [comment]
VS Code v1.22 has just been released. We can take the advantage of the new QuickPick API!!

> ### Multi-Select QuickPick
> We have added an option to the QuickPick API that makes return a list of picked items with a new UI that allows the user to pick any number of items:
> 
> ![](https://code.visualstudio.com/assets/updates/1_22/multi-select-quickpick.png)

https://code.visualstudio.com/updates/v1_22

**Comment by ryu1kn** [comment]
Released as v1.0.0 🎉

@stepbeta I'd appreciate if you can test it out 😉

**Comment by stepbeta** [comment]
Hi there!

Works pretty good, but I was a little confused at the beginning. When I'm in a diff view and toggle rules, nothing changes. I have to close the diff view and then re-apply the comparison. Is there a way to update the current view automatically?

**Comment by ryu1kn** [comment]
@stepbeta Thanks for testing it out!

Yeah, that's how it's meant to work at the moment. Updating the **current** view is not easy I guess as the extension doesn't have reference to it. Also things get complicated if we open multiple diff views.

Still I'd love to see the diff automatically gets updated when I toggle rules. Do you want to raise another issue to improve this functionality?

**Comment by stepbeta** [comment]
Done: #24 :)

Thanks for all the good work!

**Comment by ryu1kn** [comment]
Thanks @stepbeta !
