### ISSUE TITLE
Compare tab resets when focus leaves tab

### ISSUE THREAD

**Issue by FullShovelDev** [ryu1kn/vscode-partial-diff#22]
Don't think this is a bug but it would be great if the compare tab didn't reset focus back to the first match when the tab loses focus. 

Thank you!

**Comment by ryu1kn** [comment]
I can see the same behaviour on the VS Code's file comparison. I guess this is the same issue with https://github.com/Microsoft/vscode/issues/10663

Unfortunately, I don't think I can do much from partial diff side. To fix this, I wonder we need to help VS Code's diff editor itself...

**Comment by ryu1kn** [comment]
Just confirmed that, thanks to the fix on the vscode ticket, this issue has already been fixed. It doesn't go back to the first different position.
