### ISSUE TITLE
Feature request: Settings to remove individual partialDiff commands from editor context menu

### ISSUE THREAD

**Issue by bfranklyn** [ryu1kn/vscode-partial-diff#26]
![context](https://user-images.githubusercontent.com/6205670/40246910-23d3a192-5a90-11e8-9b2c-4b03016caf95.png)

**Comment by ryu1kn** [comment]
Released as v1.2.0 :tada:

**Comment by eamodio** [comment]
@ryu1kn any chance for more granularity on this setting?

Maybe something like:
```json
"partialDiff.hideCommandsOnContextMenu": [
    "SelectForCompare", 
    "ComparePrevious",
    "CompareClipboard",
    "CompareVisibleEditors",
    "PreCompare"
]
```

or
```json
"partialDiff.hideCommandsOnContextMenu": {
    "SelectForCompare": false, 
    "ComparePrevious": false,
    "CompareClipboard": true,
    "CompareVisibleEditors": true,
    "PreCompare": true
}
```

Or some way to keep some options, but remove others?

**Comment by ryu1kn** [comment]
Hi @eamodio , sure thing. Do you mind telling me the motivation for that? e.g. You normally use only `foo` and `bar`; therefore only want to see them on the context menu.

**Comment by eamodio** [comment]
Sure. I only use select and compare with previous so I'd like only those on the menu
