### ISSUE TITLE
Doesn't work at all?

### ISSUE THREAD

**Issue by GandalfSaxe** [ryu1kn/vscode-partial-diff#29]
After installing the extension and restating VSC, if I search for `partialDiff` in the keybindings, I get nothing. Also don't see any menu item starting with "PartialDiff" in the right-click context menu on any selected text.

I'm using Insiders 1.27 and on macOS 10.14 Beta (18A353d). Shouldn't this work?

**Comment by ryu1kn** [comment]
Just checked with my environment, it looks all good: code v1.26.0, macOS 10.13.

Can you check with code v1.26?

<img width="488" alt="context-munu" src="https://user-images.githubusercontent.com/1505715/44126117-b14e2342-a079-11e8-9580-20922128b465.png">

<img width="841" alt="keyboard-shortcuts" src="https://user-images.githubusercontent.com/1505715/44126124-bced8fee-a079-11e8-8581-a8f9bd9fa02a.png">

**Comment by ryu1kn** [comment]
No follow up information. Closing this off...

**Comment by GandalfSaxe** [comment]
Sorry, got busy with thesis.

Ah my bad, it works fine. I was looking for a menu item starting with `PartialDiff: ...` as on the GIF that plays in the extension marketplace site + repository README, therefore I wasn't sure if it was from PartialDiff extension or not:

![](https://raw.githubusercontent.com/ryu1kn/vscode-partial-diff/master/images/public.gif)

**Comment by ryu1kn** [comment]
Ah i see. Yeah I haven’t updated the gif animation for a while...

Thanks for confirming!!
