### ISSUE TITLE
Compare text in 2 visible editors (i.e. tabs) not working

### ISSUE THREAD

**Issue by gbritton1** [ryu1kn/vscode-partial-diff#35]
See screenshot
![snag_14808abd](https://user-images.githubusercontent.com/12263288/51037924-b13b6380-157f-11e9-8c73-7095aa9d8fc2.png)
![image](https://user-images.githubusercontent.com/12263288/51037938-bb5d6200-157f-11e9-846d-10b22568086b.png)

**Comment by ryu1kn** [comment]
Hi @gbritton1 , thanks for the screenshots! They helped me to understand what's happening. You need to have the 2 tabs open side-by-side as this command compares 2 "visible" editors. Looks like what you're after is #33 😉

**Comment by rcheung9** [comment]
Yea I have this open side by side and it still says "Please first open 2 documents to compare".

**Comment by catch6** [comment]
So why not let the user choose the file to compare.
Splitting the window is a redundant action

**Comment by JoshLambda** [comment]
> Hi @gbritton1 , thanks for the screenshots! They helped me to understand what's happening. You need to have the 2 tabs open side-by-side as this command compares 2 "visible" editors. Looks like what you're after is #33 😉

That's not what the error message says: "Please first open 2 documents to compare"
It doesn't say they have to be open side-by-side
