### ISSUE TITLE
Inability to diff whitespace

### ISSUE THREAD

**Issue by BookOfGreg** [ryu1kn/vscode-partial-diff#36]
Firstly thanks for the extension, it does really help.

Recently I was diffing two RFCs to see the difference:
[One ](https://tools.ietf.org/html/rfc7386)and [Two ](https://tools.ietf.org/html/rfc7396)and I should see the [errata](https://www.rfc-editor.org/errata_search.php?rfc=7386) in the diff but I do not as the errata was whitespace.

See attached screenshot:
![image](https://user-images.githubusercontent.com/637868/51483363-cccd1800-1d90-11e9-9fd0-f0df673ad127.png)

**Comment by ryu1kn** [comment]
Hello @BookOfGreg , I'm not sure if I get you right but if you meant that the whitespace (i.e. indentation) difference was not highlighted, you can actually visualise them as a diff by toggling **Diff Editor: Ignore Trim Whitespace** setting. It's not a Partial diff setting but the editor's diff view setting.

<img width="990" alt="screen shot 2019-01-22 at 11 57 43 pm" src="https://user-images.githubusercontent.com/1505715/51537288-37ba4400-1ea2-11e9-81fc-81fe1f61840c.png">

**Comment by BookOfGreg** [comment]
That was it. Thanks! Seems like a strange thing to have as a default in VSCode but this isn't an issue here.
