### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by chnjames** [ryu1kn/vscode-partial-diff#39]
- Issue Type: `Performance`
- Extension Name: `partial-diff`
- Extension Version: `1.4.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\14272\ryu1kn.partial-diff-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ryu1kn** [comment]
Um... did you forget to attach the profile file?

https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load#dealing-with-high-cpu-load-issues
