### ISSUE TITLE
[Suggestion] Use clipboard and current selection to compare

### ISSUE THREAD

**Issue by esquevin** [ryu1kn/vscode-partial-diff#4]
Seems to me that the flow could be simplified by using the clipboard buffer and the current selection to define text to compare.TextMate had this and it was awesome. 

You select your first text by copying it, then you go to the second text and select it, finally you run a command `Compare clipboard with selection`

**Comment by esquevin** [comment]
I'd say that the simplicity is in the number of custom commands to remember / use. The way it's currently implemented I need to use 2 custom commands, the way Textmate did it only required one.

Not wanting to overwrite the clipboard content to do a diff do not seem a frequent case for me, and either way one that should be rather dealt with clipboard history which is a very different feature

**Comment by ryu1kn** [comment]
Ah I see what you mean. In TextMate, you highlight the 2nd text and do `Compare clipboard with selection`. I thought you highlight it and do "mark 2nd text" kind of command before you issue the compare command.

Yet I still don't find a strong enough motivation to change the current behaviour, and I kind of like the current flow better. I don't want to push (or hope) people to have a clipboard history if they find partial-diff overwriting the clipboard annoying.

Let me close this issue for now, if other people also prefer the TextMate way, I'll consider this again. Thank you for your suggestion anyway 👍
