### ISSUE TITLE
[Request] Customize styles

### ISSUE THREAD

**Issue by imperativeOO** [ryu1kn/vscode-partial-diff#40]
Hey,

thanks for this great extension. I couldn't find any way to customize the highlighting styles in the diff view though. Maybe I'm just blind?

In case there are indeed no options, I'd like to suggest some options here. To quickly glance over a diff it would be nice if not the whole line is highlighted (and the difference in a darker color) but to only highlight the difference.

Or maybe make the line highlighting more subtle so it can either be ignored more easily or at least more easily be distinguished from the difference in the line.

**Comment by ryu1kn** [comment]
Hi @imperativeOO , sorry for having taken long to respond. Partial diff is using just VS Code's diff editor. I wonder if you can configure colours to your needs with something like below. There may be other `diffEditor.` properties we can specify.

https://stackoverflow.com/questions/49036101/how-to-change-diff-color-visual-studio-code
