### ISSUE TITLE
Clipboard diff does not work  with VS code 3.15 in remote ssh

### ISSUE THREAD

**Issue by WeiXiaoQian** [ryu1kn/vscode-partial-diff#42]
Clipboard diff does not work  with VS code 3.15 in remote ssh

**Comment by yyb196** [comment]
+1, need this feature too

**Comment by ryu1kn** [comment]
Hi @WeiXiaoQian and @yyb196 , sorry somehow I overlooked this issue. Is remote ssh an extension? Could you provide the steps to reproduce?

**Comment by WeiXiaoQian** [comment]
Hi @ryu1kn,

1. You should have a Linux server like Ubuntu, Centos.. with SSH open.
2. Install https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
3. Use remote ssh extension connect your Linux host via SSH.
4. Then the Clipboard diff does not work properly.

Thanks.

**Comment by ryu1kn** [comment]
Upon calling **Compare Text with Clipboard**

![image](https://user-images.githubusercontent.com/1505715/73065445-adaf1c00-3ef7-11ea-9904-f44159d27230.png)

After installing xsel on SSH-ed machine

![image](https://user-images.githubusercontent.com/1505715/73065665-3928ad00-3ef8-11ea-8939-abdcf9a65a7f.png)

I wonder if replacing Clipboardy with [VS Code's Clipboard API](https://code.visualstudio.com/api/references/vscode-api#Clipboard) can solve the problem 🤔

**Comment by ryu1kn** [comment]
Memo: Used [ubuntu-sshd](https://hub.docker.com/r/rastasheep/ubuntu-sshd/) to run a SSH daemon for testing.

**Comment by ryu1kn** [comment]
Promising https://code.visualstudio.com/blogs/2019/05/02/remote-development#_extension-authors

**Comment by ryu1kn** [comment]
Fixed in v1.4.1 ✅
