### ISSUE TITLE
Full diff sometimes compares second file to itself

### ISSUE THREAD

**Issue by MatthewFergus** [ryu1kn/vscode-partial-diff#43]
Using this feature listed in the readme:

> Executing Select Text for Compare, Compare Text with Previous Selection or Compare Text in
> Visible Editors command without selecting any text will use the entire text of the current file.

I right click with no selection in my first file and choose Select Text for Compare, then right click and choose Compare Text with Previous Selection in the second. Sometimes when I do this the diff incorrectly shows the diff between the second file and itself. This can be easy to miss if the two files have the same name, leading you to think there are no differences when there actually are. This has got me a few times now. If I repeat the steps the diff is shown correctly.

I can reliably reproduce this by opening two files, relaunching visual studio code and quickly diff them just after the files reopen.

**Comment by ryu1kn** [comment]
Thanks for reporting it. Interesting, I wonder if the extension is not loaded up yet when this happens.
Do you see any errors if you open "Toggle Developer Tools"?

**Comment by MatthewFergus** [comment]
No worries. I had a look and can't see any errors in the developer tools console after triggering the issue.

**Comment by ryu1kn** [comment]
Thanks @MatthewFergus for checking the console output. The extension only starts when we trigger one of [those commands](https://github.com/ryu1kn/vscode-partial-diff/blob/140450883503c41c475f2496f9e1ce0baae34af6/package.json#L28); so it still makes sense that relaunching is the way to reproduce it.

**Comment by ryu1kn** [comment]
Fixed in v1.4.1 ✅
