### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by samael205** [ryu1kn/vscode-partial-diff#46]
[ryu1kn.partial-diff-unresponsive.cpuprofile.txt](https://github.com/ryu1kn/vscode-partial-diff/files/4128435/ryu1kn.partial-diff-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `partial-diff`
- Extension Version: `1.4.1`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Becario\ryu1kn.partial-diff-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by victoriafrench** [comment]
[ryu1kn.partial-diff-unresponsive.cpuprofile.txt](https://github.com/ryu1kn/vscode-partial-diff/files/4594388/ryu1kn.partial-diff-unresponsive.cpuprofile.txt)

`OSX 10.13.6` with `Node 10.20.1` as well

**Comment by liboshu** [comment]
[ryu1kn.partial-diff-unresponsive.cpuprofile.txt](https://github.com/ryu1kn/vscode-partial-diff/files/4799144/ryu1kn.partial-diff-unresponsive.cpuprofile.txt)

**Comment by iskandersierra** [comment]
[ryu1kn.partial-diff-unresponsive.cpuprofile.txt](https://github.com/ryu1kn/vscode-partial-diff/files/5266309/ryu1kn.partial-diff-unresponsive.cpuprofile.txt)

**Comment by ryu1kn** [comment]
Additional info on https://github.com/ryu1kn/vscode-partial-diff/issues/48

**Developer: Show Running Extensions** shows how much time running extensions took when they started.

**Comment by ryu1kn** [comment]
Just took a look at all 4 uploaded cpu profiles. They all seem to be taking time with loading modules. I'm wondering if this is this case

https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load#code-loading

I'm thinking to try bundling js files with webpack or something as suggested.

**Comment by ryu1kn** [comment]
Bundle js files with webpack and the extension startup times has improved 154 ms to 7.8 ms (10 times run average), 95% reduction 😮 

Please let me know if you still see the issue.
