### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by BannerBomb** [ryu1kn/vscode-partial-diff#48]
- Issue Type: `Performance`
- Extension Name: `partial-diff`
- Extension Version: `1.4.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.42.1`

Extension is showing as unresponsive for me.

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 5182,
		"activateCallTime": 7,
		"activateResolvedTime": 1098,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "ryu1kn.partial-diff",
				"_lower": "ryu1kn.partial-diff"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by ryu1kn** [comment]
Hi @BannerBomb , can you provide the steps to reproduce this so that I can have a look at this? Does this happen whenever you just start Code? Happens when you open a particular folder/workspace? etc. Thanks!

**Comment by BannerBomb** [comment]
it starts when I open vsc

**Comment by ryu1kn** [comment]
Thanks for the additional info!

**Comment by tjx666** [comment]
![screenshot_2020-07-24_00-31-21](https://user-images.githubusercontent.com/41773861/88312685-03e50680-cd45-11ea-9246-2e786966c40e.png)

**Comment by BannerBomb** [comment]
Yes just like the above image, except mine was for Startup Activation at the time. Mine is fixed ever since I bought a gaming laptop though.

**Comment by ryu1kn** [comment]
Consolidating to https://github.com/ryu1kn/vscode-partial-diff/issues/46
