### ISSUE TITLE
Filter / Ignore Regex Matches

### ISSUE THREAD

**Issue by Chiramisu** [ryu1kn/vscode-partial-diff#49]
What would make this extension totally boss and superior to any other diffing / compare tool I've ever used, is if it had the ability to add a Regex filter to ignore certain conditions in the comparison. For example, many times I want to compare log files that have timestamps in them, but I only need to compare the content, and timestamps just clutter up the diff making it substantially more work to visually identify lines with actual different content.

I should be able to set any number of Regex filters and any text that matches the pattern should be completely ignored by the diff. 🚀👍🏼

Why nobody has thought of this, I'll never know. Sky's the limit. Useful not just for timestamps, but hashes, UUIDs, random numbers, anything that varies consistently between files of the same ilk that isn't germane to the diffing at hand. 😉

**Comment by ryu1kn** [comment]
I wonder if this option helps you achieve what you want.

> * `partialDiff.preComparisonTextNormalizationRules` (default: `[]`)
>   
>   Rules to normalize texts for diff view.
>   
>   It doesn't mutate texts in the editors. Only texts in diff views get normalised. If a diff is presented with text normalised (or possibly normalised), `~` is used in the diff title instead of `↔`)

from [README](https://github.com/ryu1kn/vscode-partial-diff/blob/3833b71809c3b17ba3a9bd3ec3c11bee5e0385e4/README.md)

For example, you can remove timestamp differences from the diff with following setting (and enable it with `Toggle Pre-Comparison Text Normalization Rules` command).

```json
"partialDiff.preComparisonTextNormalizationRules": [
    {
      "name": "Replace timestamp with dummy value",
      "match": "\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z",
      "replaceWith": "0000-00-00T00:00:00.000Z",
      "enableOnStart": false
    }
]

**Comment by ryu1kn** [comment]
I'm closing this. If the above doesn't solve your problem, let me know 👍

**Comment by ryu1kn** [comment]
Hi @CasperLange 👋  Would be great if you can share a sample repx-file with a diff screenshot. I've just tested it like this:

Dummy text:

```
## TEXT 1
Ref=1
Name="name-1"
Dpi="254"

## TEXT 2
Ref=2
Name="name-2"
Dpi="369"
```

The normalisation rules:

```json
  "partialDiff.preComparisonTextNormalizationRules": [
    {
      "name": "Ignore Ref no",
      "match": "Ref=\\d+",
      "replaceWith": "Ref=__ignore_ref__",
      "enableOnStart": true
    },
    {
      "name": "Ignore name",
      "match": "Name=\"[^\\\"]*\"",
      "replaceWith": "Name=\"__ignore_name__\"",
      "enableOnStart": true
    },
    {
      "name": "Ignore name",
      "match": "Dpi=\"\\d+\"",
      "replaceWith": "Dpi=\"__ignore_dpi__\"",
      "enableOnStart": true
    }
  ],
```

This looks fine to me.

<img width="791" height="164" alt="Image" src="https://github.com/user-attachments/assets/66663629-b3fc-4e6e-89a6-dfa308fc4ffc" />
