### ISSUE TITLE
Diff with file on remote branch

### ISSUE THREAD

**Issue by rndware** [ryu1kn/vscode-partial-diff#53]
Currently there is not a plugin I'm aware of that can do a diff between the currently opened file and the same one on a specified branch name.

This is extremely handy if you're working on a feature branch, master gets updated, and you want to check what conflicts might arise if you attempt to merge the file.

I've just created a working POF:

https://github.com/ryu1kn/vscode-partial-diff/pull/52

I'm wondering if this could be part of a forked 'git diff' type of extension that could diff between refs of all different types.

Food for thought :)

**Comment by ryu1kn** [comment]
Thanks for the idea. That would be handy though that would be a feature for "git diff" type extension as you wrote. It would essentially be:

```sh
git diff origin/remote-branch-name -- path/to/file-for-comparison.txt
```

**Comment by ryu1kn** [comment]
I'm closing this for now, but feel free to reopen it if you think we should continue exploring this.
