### ISSUE TITLE
put all the context menu items in partial diff submenu

### ISSUE THREAD

**Issue by tjx666** [ryu1kn/vscode-partial-diff#55]
Now, the menu items of partial diff takes a lot of display space of context menu.

**Comment by ryu1kn** [comment]
For the commands you don't use so often, you can hide them from the context menu with `partialDiff.commandsOnContextMenu`. If you want to run a hidden command, you can still use from Cmd + Shift + P (or Ctrl + Shift + P on Windows/Linux) and start typing "PartialDiff" to filter only this extension command.

Would it solve your problem?

**Comment by tjx666** [comment]
I think it's ok
