### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by milovan-minic** [ryu1kn/vscode-partial-diff#57]
- Issue Type: `Bug`
- Extension Name: `partial-diff`
- Extension Version: `1.4.1`
- OS Version: `Linux x64 5.4.0-52-generic`
- VSCode version: `1.49.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ryu1kn** [comment]
Hi @milovan-minic , sorry for my late response. Do you have additional info on what the "Bug" was?

**Comment by ryu1kn** [comment]
Closing this. Feel free to reopen it once you have more details
