### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by KolyaKorruptis** [ryu1kn/vscode-partial-diff#59]
Our company has a donations program for open source projects that we use on the job. 
But I don't see a way to donate for the development of this extension.

**Comment by ryu1kn** [comment]
Thank you for considering supporting/encouraging the work. I've enabled **Sponsor** button on this repository 😃

**Comment by KolyaKorruptis** [comment]
Is there any way to give you a one-time donation? Maybe I'm not seeing it. An email address should be fine.
