### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by peterson21988** [ryu1kn/vscode-partial-diff#63]
- Issue Type: `Bug`
- Extension Name: `partial-diff`
- Extension Version: `1.4.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ryu1kn** [comment]
Sorry I can't take a closer look at this as the "needed data" seems to be not provided...

Is this a dup of https://github.com/ryu1kn/vscode-partial-diff/issues/46 ?
