### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by baayuraas** [ryu1kn/vscode-partial-diff#65]
- Issue Type: `Bug`
- Extension Name: `partial-diff`
- Extension Version: `1.4.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.1`

**Comment by ryu1kn** [comment]
Sorry I can't take a closer look at this as the "needed data" seems to be not provided...

Is this a dup of #46 ?
