### ISSUE TITLE
Problema de extensión

### ISSUE THREAD

**Issue by samborski** [ryu1kn/vscode-partial-diff#68]
- Issue Type: `Bug`
- Extension Name: `partial-diff`
- Extension Version: `1.4.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ryu1kn** [comment]
Hi @samborski , it seems you forgot to paste *the needed data*. Are you able to reproduce the issue and paste the data?

**Comment by ryu1kn** [comment]
Closing this...
