### ISSUE TITLE
Rule to compare selection.

### ISSUE THREAD

**Issue by carlosmgilp** [ryu1kn/vscode-partial-diff#69]
Is there any way that I can compare two pieces of code, but it is only the code, not what line it is on.
The code is from Autocad autolisp extension.
I have two code snippets

```lisp
;#region check ss
; Selection
(defun selectionlisp1 (/ sset check) 
  ;load the visual lisp extensions
  (vl-load-com)
  ;check for selection
  (while (setq sset (car (entsel))) 
    (setq sset (vlax-ename->vla-object sset))
    (setq check (vlax-property-available-p sset "Color" T))
    (if check 
      (vlax-put-property sset 'Color 4)))
  (princ))
;#endregion

;#region check ss
; Selection
(defun selectionlisp1 (/ sset check) 
  ;load the visual lisp extensions
  (vl-load-com)
  ;check for selection
  (while (setq sset (car (entsel))) 
    (setq sset (vlax-ename->vla-object sset))
    (setq check (vlax-property-available-p sset "Color" T))
    (if check (vlax-put-property sset 'Color 4)))
  (princ))
;#endregion
```

Both are the same, it only changes that one line is on another, but the code still works.
Comparing the selections shows me a difference, but there should be no difference because the code is the same.
How can I improve this. 
Thanks.

**Comment by ryu1kn** [comment]
Hi @carlosmgilp , Partial diff doesn't know if those lines are semantically the same, as it only does text comparison.

However, if just ignoring the line break difference does the job, you can use `partialDiff.preComparisonTextNormalizationRules` with something like this:

```json
  "partialDiff.preComparisonTextNormalizationRules": [
    {
      "name": "Ignore line breaks",
      "match": "\n+",
      "replaceWith": " "
    }
  ]
```

**Comment by carlosmgilp** [comment]
Hello @ryu1kn how are you.
Thanks for your answer.

I don't really understand how the rule works.

1. I keep the rule.

![01](https://user-images.githubusercontent.com/80189444/115496933-af6da980-a238-11eb-8224-3635ad26fc92.jpg)

2. I verify that it is active.

![02](https://user-images.githubusercontent.com/80189444/115496949-b8f71180-a238-11eb-9ed0-7fd0a8ddf409.jpg)

3. Here I show where the line that goes down is.

![03](https://user-images.githubusercontent.com/80189444/115496962-c14f4c80-a238-11eb-9de0-80b8558606c2.jpg)

4. I select the text to compare.

![04](https://user-images.githubusercontent.com/80189444/115496976-c90ef100-a238-11eb-9231-73f1498c2c79.jpg)

5. I compare with the previous selection.

![05](https://user-images.githubusercontent.com/80189444/115497008-d75d0d00-a238-11eb-963c-4c3cabc7b5e7.jpg)

6. But it still shows me the difference.

![06](https://user-images.githubusercontent.com/80189444/115497030-ddeb8480-a238-11eb-86e7-050b9f1590c8.jpg)

Could you explain to me what I'm doing wrong.
Thank you in advance.

**Comment by ryu1kn** [comment]
Ah, in your first comment, all lines didn't have indentations. I've updated it to use a code block to keep the indentations.

With the leading indentation, the regex I posted above doesn't work. Something like this would do `"match": " *\n +"`. The comparison result should look like this (no difference).

![image](https://user-images.githubusercontent.com/1505715/115534474-29566f00-a2db-11eb-8911-2982e32148b0.png)

**Comment by carlosmgilp** [comment]
Hi @ryu1kn , thanks again for your time to help me.

But it doesn't work for me.

Save the new rule.

![07](https://user-images.githubusercontent.com/80189444/115595104-884cc180-a2a4-11eb-99b4-6c624929790b.jpg)

Verify that it was active.

![08](https://user-images.githubusercontent.com/80189444/115595129-900c6600-a2a4-11eb-833e-5a331e37cb23.jpg)

I made the previous selection.
Then select the text to compare.
And this is the result it gives me.

![image](https://user-images.githubusercontent.com/80189444/115595250-b205e880-a2a4-11eb-9bc4-685fdc4c6fdb.png)

In what you can help me, I appreciate it.

**Comment by ryu1kn** [comment]
Are you using Windows? Is your line ending character `CRLF` but not `LF`? In which case, the regex needs to be `"match": " *\r\n +"`

**Comment by carlosmgilp** [comment]
Hello Brother how are you.
Excuse me for not specifying the operating system.
I work with windows.
Thank you. Now if it works very well.
I don't understand why it puts all the code on one line.
If that could be improved in the future, it would be much better.
If it were shown as the example image it would be spectacular.

![13](https://user-images.githubusercontent.com/80189444/115656193-bcef6600-a302-11eb-8412-99a6ab92ccb4.jpg)

Thank you very much for helping me, for your time and dedication.
Greetings and many successes.

**Comment by ryu1kn** [comment]
@carlosmgilp It puts all the code on one line because the below normalisation rule instructs to replace strings that match regex ` *\r\n +` to a single space character. We can improve this normalisation rule but as the extension doesn't know the language syntax (it doesn't have a lisp parser), it would be limited.

```json
  "partialDiff.preComparisonTextNormalizationRules": [
    {
      "name": "Ignore line breaks",
      "match": " *\r\n +",
      "replaceWith": " "
    }
  ]
```

**Comment by ryu1kn** [comment]
I'm closing this...
