### ISSUE TITLE
[question]Does it can compare code in different window?

### ISSUE THREAD

**Issue by Yuzeyang** [ryu1kn/vscode-partial-diff#7]

**Comment by ryu1kn** [comment]
I haven't tried it myself but I wouldn't get surprised if it doesn't.

But you can copy first text into your OS clipboard, and go to the other window and use "Compare Text with Clipboard" command to take a diff. With the "Compare Text with Clipboard" command, as long as one of the text is in vscode, you can compare.

**Comment by ryu1kn** [comment]
Did my previous comment help you in any way? I'm closing this issue.

**Comment by Yuzeyang** [comment]
@ryu1kn thanks for your answer~
