### ISSUE TITLE
Feature Request: Support for word wrap in a diff window

### ISSUE THREAD

**Issue by kimptoc** [ryu1kn/vscode-partial-diff#8]
Thanks for the great tool.

Any plans to support word wrap in a diff window - assuming its a limitation in the plugin...

Would be handy for comparing very long lines!

Thanks.

**Comment by ryu1kn** [comment]
Hi. Hmm... word wrap doesn't seem to be supported even on the standard file compare or git diff. Since partial diff just use VSCode's diff view `vscode.diff` (https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands), I don't think I can do much about it...

**Comment by kimptoc** [comment]
Ok - I see that its been requested there - https://github.com/Microsoft/vscode/issues/11387  :)

**Comment by ryu1kn** [comment]
Cool, thanks for finding the issue! Let's wait for them supporting it 😉

**Comment by ryu1kn** [comment]
> Ok - I see that its been requested there - [microsoft/vscode#11387](https://github.com/microsoft/vscode/issues/11387) :)

This has been addressed and just released as 1.52.0!! 🎉
